services:
  db:
    image: postgres:16
    container_name: quiniela_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: quiniela
      POSTGRES_PASSWORD: quiniela123
      POSTGRES_DB: quiniela
    ports:
      - "5432:5432"
    volumes:
      - quiniela_pgdata:/var/lib/postgresql/data

volumes:
  quiniela_pgdata: